#!/usr/bin/env bash

##############################################################################
# Testing Framework & Utilities
##############################################################################

fatal() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
  exit 1
}

assert_eq() {
  local test_id="$1"
  local expect="$2"
  local actual="$3"
  if [[ "${expect}" != "${actual}" ]]; then
    fatal "assert_equal::${test_id} expect=${expect} got=${actual}"
  fi
}

assert_neq() {
  local test_id="$1"
  local expect="$2"
  local actual="$3"
  if [[ "${expect}" == "${actual}" ]]; then
    fatal "assert_not_equal::${test_id} expect!=${expect} got=${actual}"
  fi
}

##############################################################################
# Tests
##############################################################################

integration__test_simple_project_names() {
  declare -Ar iterations=(
    ['portify']='53412'
    ['python']='52153'
    ['cpython']='62110'
    ['guix']='49936'
    ['emacs']='56739'
  )
  local actual
  for name in "${!iterations[@]}"; do
    local expect="${iterations[$name]}"
    actual="$(./portify "${name}")"
    assert_eq "${FUNCNAME[0]}(${name})" "${expect}" "${actual}"
  done
}

integration__test_empty_project_name() {
  local name=''
  local actual
  actual="$(./portify "${name}")"
  local expect='53412'
  assert_eq "${FUNCNAME[0]}" "${expect}" "${actual}"
}

integration__test_very_long_project_name() {
  local base='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  local name="${base}${base}${base}${base}${base}${base}${base}${base}${base}"
  local actual
  actual="$(./portify "${name}")"
  local expect='50422'
  assert_eq "${FUNCNAME[0]}" "${expect}" "${actual}"
}

integration__test_project_name_with_spaces() {
  local name='portify'
  local actual
  local unexpected
  actual="$(./portify "${name} 42 ")"
  unexpected="$(./portify "${name}")"
  assert_neq "${FUNCNAME[0]}" "${unexpected}" "${actual}"
  local expect='60497'
  assert_eq "${FUNCNAME[0]}" "${expect}" "${actual}"
}

integration__test_varargs_project_name() {
  local name='portify'
  local actual
  local unexpected
  actual="$(./portify "${name}" '42')"
  unexpected="$(./portify "${name}")"
  assert_neq "${FUNCNAME[0]}" "${unexpected}" "${actual}"
  local expect='57985'
  assert_eq "${FUNCNAME[0]}" "${expect}" "${actual}"
}

integration__test_project_name_with_dashes() {
  local name='portify'
  local actual
  local unexpected
  actual="$(./portify "${name}-42-")"
  unexpected="$(./portify "${name}")"
  assert_neq "${FUNCNAME[0]}" "${unexpected}" "${actual}"
  local expect='60499'
  assert_eq "${FUNCNAME[0]}" "${expect}" "${actual}"
}

main() {
  integration__test_simple_project_names
  integration__test_empty_project_name
  integration__test_very_long_project_name
  integration__test_project_name_with_spaces
  integration__test_varargs_project_name
  integration__test_project_name_with_dashes
}

main "$@"
